### ISSUE TITLE
[Баг] | В английской локализации присутсвует русские реплики

### ISSUE THREAD

**Issue by Redume** [Rimuwu/DinoGochi#11]
![image](https://user-images.githubusercontent.com/49362257/206925384-61389ad8-f52a-4c0c-9303-6e389037c702.png)
![image](https://user-images.githubusercontent.com/49362257/206925393-d5d004be-2332-442c-8e81-295445604589.png)

А так же может попасться реплика на русском если динозавр вернулся с прогулки

![image](https://user-images.githubusercontent.com/49362257/206925457-1e23e722-dce6-4e28-872c-c3a7acbf211e.png)

**Comment by Rimuwu** [comment]
Исправно
